spring:
  application:
    name : otp
  datasource:
    url : jdbc:postgresql://localhost:5432/postgres
    username : post
    password: post456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#server :
#  port :
